services:
  itemstore-api:
    build:
      context: PhpApi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./PhpApi/:/var/www/html
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bobbydb
      - DB_USERNAME=bobby
      - DB_PASSWORD=some_pass
    depends_on:
      - mariadb
  
  mariadb:
    build:
      context: PhpApi/docker/mariadb
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=bobbydb
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=some_pass
    volumes: 
      - ./PhpApi/creation_script.sql:/docker-entrypoint-initdb.d/01-creation_script.sql
      - mariadb_data:/var/lib/mysql

  authenticationservice:
    build:
      context: AuthenticationService
      dockerfile: AuthenticationService.API/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"

    ports:
      - "5000:5000"
    volumes:
      - ./AuthenticationService/data/:/app/data
    
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/auth.db
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    
  chatbotapi:
    build:
      context: ChatbotAPI
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    environment:
      - OLLAMA_HOST=http://ollama:11434
    
    depends_on:
      - ollama
    
    volumes: 
      - ./ChatbotAPI/:/app

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  
  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama_init
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    # Automatically pulls the specific model required by chat_service.py
    command: pull llama3.2:1b

  webui:
    build:
      context: webui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - itemstore-api
      - authenticationservice
      - chatbotapi


volumes:
  mariadb_data:
  ollama_data:
