FROM mariadb:10.11

# This is a placeholder for any future database customizations.
# You can uncomment the line below to add a startup SQL script if you create one:
# COPY ./init.sql /docker-entrypoint-initdb.d/