### GET request to example server
GET http://localhost:8080/api

### POST request

POST http://localhost:8080/api

### PUT request

PUT http://localhost:8080/api

### DELETE

DELETE http://localhost:8080/api

###