server {
    listen 8080;
    server_name localhost;

    location ^~ /api/auth/ {
        proxy_pass https://authapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /ai/ {
        proxy_pass https://chatbotapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /api/items {
        proxy_pass https://itemapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /api/purchase {
        proxy_pass https://itemapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /api/purchases {
        proxy_pass https://itemapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /api/media/ {
        proxy_pass https://mediaapi-dot-cloud-hw3-491910.ey.r.appspot.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fallback to index.html for Single Page Applications (SPA)
        try_files $uri $uri/ /index.html;
    }
}