services:
  authenticationservice.api:
    image: authenticationservice.api
    build:
      context: .
      dockerfile: AuthenticationService.API/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/auth.db
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
